import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "./_components/Navbar";
import FooterNav from "./_components/FooterNav";
import { Suspense } from 'react'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jost = Jost({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className} antialiased`}>
           <Suspense fallback={
          <div className="flex justify-center items-center h-[100vh]">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-gray-900"></div>
      </div>
        }>
           <AuthProvider>
          <div className="flex flex-col h-[92svh]">
            <Navbar />
            <div className="md:pb-0 overflow-y-auto flex-1">
              {children}
            </div>
            <FooterNav />
          </div>
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            closeOnClick
            pauseOnHover
            draggable
          />
        </AuthProvider>

        </Suspense>
       
      </body>
    </html>
  );
}
